version: "3.7"

services:
        django:
                container_name: django
                image: emma0415/django:3.2.3
                environment:
                        - DJANGO_SETTINGS_MODULE=config.settings.prod
                ports:
                        - 52222:52222  # API service port
                volumes:
                        - ./django:/usr/src/django
                depends_on:
                        # - nginx
                        - postgresql
                          # command:
                          # - python manage.py runserver 0.0.0.0:52222 --settings=config.settings.prod
                links:
                        - postgresql:POSTGRESQL_ADDR # <service>:<alias>
                entrypoint:
                        - /bin/bash
                tty: true
                stdin_open: true

        postgresql:
                container_name: postgresql
                image: postgres:13.3
                ports:
                        - 5432:5432
                volumes:
                        - ./postgres/data:/var/lib/postgresql/data
                environment:
                        - POSTGRES_PASSWORD=''

        nginx:
                container_name: nginx
                image: nginx:1.21.0
                ports:
                        - 80:80
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/conf.d/:/etc/nginx/conf.d/
                        - ./html/:/usr/share/nginx/html/
                links:
                        - django:DJANGO_ADDR