version: "3.7"

services:
        django:
                container_name: django
                image: emma0415/django:3.2.3
                environment:
                        - DJANGO_SETTINGS_MODULE=config.settings.prod
                        - DJANGO_SETTINGS_MODULE=config.settings.local
                volumes:
                        - ./django/:/usr/src/django/
                        - ./frontend/dist/static/:/usr/src/django/.static_root/
                depends_on:
                        - postgresql
                command:
                        - gunicorn
                        - config.wsgi:application
                        - --bind
                        - 0.0.0.0:52222
                        - --reload
                links:
                        - postgresql:POSTGRESQL_ADDR # <service>:<alias>

        postgresql:
                container_name: postgresql
                image: postgres:13.3
                ports:
                        - 5432:5432
                volumes:
                        - ./postgres/data:/var/lib/postgresql/data
                environment:
                        - POSTGRES_PASSWORD=''

        nginx:
                container_name: nginx
                image: nginx:1.21.0
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/conf.d/:/etc/nginx/conf.d/
                        - ./frontend/dist/:/usr/share/nginx/html/  # static page
                links:
                        - django:DJANGO_ADDR
